Select * from Transactions;
select * from prod_cat_info;
Select * from Customer;

--DATA PREPARATION AND UNDERSTANDING
--1. What is the total number of rows in each of the 3 tables in the database?
Select Count(*) as cnt From Customer
UNION
Select Count(*) as cnt From prod_cat_info
UNION
Select Count(*) as cnt From Transactions;

--2. What is the total number of transactions that have a return?
Select Count(Distinct(transaction_id)) as ret_tran
From Transactions
Where qty < 0;

--3. As you would have noticed, the dates provided across the datasets are not in a correct format. As first steps, pls convert the date variables into valid date formats before proceeding ahead.
Select CONVERT(Date,tran_date,105) as tran_dates 
from Transactions;

--4. What is the time range of the transaction data available for analysis? Show the output in number of days, months and years simultaneously in different columns.
Select DATEDIFF(YEAR,MIN(CONVERT(Date,tran_date,105)),MAX(CONVERT(Date,tran_date,105))) As diff_years,
DATEDIFF(MONTH,MIN(CONVERT(Date,tran_date,105)),MAX(CONVERT(Date,tran_date,105))) As diff_Month,
DATEDIFF(DAY,MIN(CONVERT(Date,tran_date,105)),MAX(CONVERT(Date,tran_date,105))) As diff_days
From Transactions;

--5. Which product category does the sub-category "DIY" belong to?
Select prod_cat,prod_subcat 
From prod_cat_info
Where prod_subcat='DIY';

--DATA ANALYSIS                                                                    
--1. Which channel is most frequently used for transactions?
Select TOP 1 Store_type,Count(*) as Cnt 
From Transactions
Group By Store_type
Order By Cnt desc;

--2. What is the count of Male and Female customers in the database?S
SELECT Gender,Count(*) as no_of_customers
From Customer
Where Gender IS NOT Null
Group By Gender;

--3. From which city do we have the maximum number of customers and how many?
SELECT TOP 1 city_code,Count(customer_id) as no_of_customers
From Customer
Group by city_code
Order by no_of_customers Desc;

--4. How many sub-categories are there under the Books category?
Select prod_subcat from prod_cat_info
Where prod_cat = 'Books';

--5. What is the maximum quantity of products ever ordered?
Select prod_cat,Max(t.Qty) as Max_quantity
From prod_cat_info p
JOIN
Transactions t
on p.prod_cat_code=t.prod_cat_code
Group by prod_cat;

--6. What is the net total revenue generated in categories Electronics and Books?
Select SUM(Cast(t.total_amt as float)) as total_revenue
From prod_cat_info p
JOIN
Transactions t
on p.prod_cat_code=t.prod_cat_code AND p.prod_sub_cat_code=t.prod_subcat_code
Where prod_cat ='Books'OR prod_cat='Electronics';

--7. How many customers have >10 transactions with us, excluding returns?
Select Count(*) as tot_cust 
From(
	Select cust_id,Count(distinct(transaction_id)) as cnt_trans
	From Transactions
	Where qty > 0
	Group By cust_id
	Having Count(distinct(transaction_id)) > 10
	) as T1;

--8. What is the combined revenue earned from the "Electronics" & "Clothing" categories, from "Flagship stores"?
Select SUM(CAST(total_amt as FLOAT)) as Combined_revenue
From prod_cat_info p
JOIN
Transactions t
on p.prod_cat_code=t.prod_cat_code AND p.prod_sub_cat_code= t.prod_subcat_code
Where prod_cat IN ('Clothing','Electronics') AND Store_type ='Flagship store' AND qty>0;

--9. What is the total revenue generated from "Male" customers in "Electronics" category? Output should display total revenue by prod sub-cat.
Select  prod_subcat,
Sum(Cast(t.total_amt as float)) as total_revenue
From Customer c
JOIN
Transactions t
on c.customer_Id=t.cust_id
JOIN
prod_cat_info p
on p.prod_cat_code=t.prod_cat_code AND p.prod_sub_cat_code= t.prod_subcat_code
Where  p.prod_cat ='Electronics' AND c.Gender ='M'
Group by prod_subcat;

--10. What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
Select t1.prod_subcat,t1.percentage_sales,t2.percentage_return
From
(Select TOP 5 prod_subcat,
(Sum(Cast(total_amt as float))/(Select Sum(Cast(total_amt as float)) as total_sales 
								From Transactions
								Where Qty>0)) as percentage_sales
From prod_cat_info p
JOIN
Transactions t
on p.prod_cat_code=t.prod_cat_code AND p.prod_sub_cat_code= t.prod_subcat_code
Where qty>0
Group by prod_subcat
Order By percentage_sales desc
) as t1
JOIN
(Select prod_subcat,
(Sum(Cast(total_amt as float))/(Select Sum(Cast(total_amt as float)) as total_sales 
								From Transactions
								where Qty<0)) as percentage_return
From prod_cat_info p
JOIN
Transactions t
on p.prod_cat_code=t.prod_cat_code AND p.prod_sub_cat_code= t.prod_subcat_code
Where qty<0
Group by prod_subcat) as t2
on t1.prod_subcat=t2.prod_subcat;

--11. For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 30 days of transactions from max transaction date available in the data?
Select * from
(
Select cust_id,DATEDIFF(Year,dob,max_date) as age,revenue
From
(
Select Cust_id,dob,
Max(convert(Date,tran_date,105)) as max_date,
Sum(Cast(total_amt as float)) as revenue
from Customer c
JOIN 
Transactions t
On c.customer_Id=t.cust_id
Where qty >0
Group by cust_id,DOB
) as A
where DATEDIFF(Year,dob,max_date) Between 25 and 35
) as B
JOIN 
(
Select cust_id,Convert(Date,tran_date,105) as tran_date
From Transactions
Group by cust_id,Convert(Date,tran_date,105)
Having Convert(Date,tran_date,105) >= (Select DATEADD(day,-30,
                                       Max(convert(Date,tran_date,105))) as
									   cutoff_date From Transactions)
)as C
on B.cust_id=C.cust_id;

--12. Which product category has seen the max value of returns in the last 3 months of transactions?
Select TOP 1 prod_cat_code,Sum(returns) as tot_returns 
From
(
Select  prod_cat_code,convert(date,tran_date,105) as tran_date,sum(qty) as returns
From Transactions
Where qty < 0
Group by prod_cat_code,convert(date,tran_date,105)
Having convert(date,tran_date,105) >= (Select DATEADD(Month,-3,
                                       max(convert(date,tran_date,105))) as
									   cutoff_date from Transactions)
) As A
Group by prod_cat_code
order by tot_returns


--13. Which store-type sells the maximum products; by value of sales amount and by quantity sold?
Select Store_type,Sum(total_amt) as total_sum,SUM(Qty) as no_of_quantity
From Transactions
Where qty > 0
Group by Store_type
order by total_sum Desc,no_of_quantity Desc;

--14. What are the categories for which average revenue is above the overall average.
Select prod_cat,avg(total_amt) as avg_revenue
From Transactions t
join
prod_cat_info p
on t.prod_cat_code=p.prod_cat_code
Where qty>0
Group by prod_cat
Having avg(total_amt) >= (Select avg(total_amt) as overall_avg
                         from Transactions
						 Where qty>0);

--15. Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.
Select prod_subcat_code,
Sum(cast(total_amt as float)) as revenue,
Avg(cast(total_amt as float)) as avg_revenue
From Transactions
Where qty > 0 and prod_cat_code in (Select top 5 prod_cat_code 
                                   From Transactions
								   Where qty > 0
								   Group by prod_cat_code
								   Order by Sum(Qty) Desc )
Group by prod_subcat_code;







